todo: main.o bd.o tabla.o tablas.o columnas.o
	g++ -Wall -o main.o bd.o tabla.o tablas.o columnas.o
main.o: main.cpp
	g++ -Wall -c main.cpp
bd.o: bd.cpp bd.h
	g++ -Wall -c bd.cpp
tabla.o: tabla.cpp tabla.h
	g++ -Wall -c tabla.cpp
tablas.o: tablas.cpp tablas.h
	g++ -Wall -c tablas.cpp
columnas.o: columnas.cpp columnas.h
	g++ -Wall -c columnas.cpp
clean:
	rm -f *.o
	rm -f main

